### ISSUE TITLE
Conda install

### ISSUE THREAD

**Issue by mg3146** [pyxll/pyxll-jupyter#27]
Hi,

Are you able to provide directions on how to use conda to install?  I have multiple virtual environments (with diff python versions than base/root..), so pip a bit dicey to use.  But I'm not really sure how to use conda to do it...

Thanks!

**Comment by tonyroberts** [comment]
Check the conda docs for how to build a conda package if you don't want to use a wheel. I seem to recall the recommendation for using wheels with conda is to use "pip install --no-deps <name>" when the dependencies are already installed using conda. For this project the only dependency you need to install is jupyter.
