### ISSUE TITLE
It doesn't support Mac

### ISSUE THREAD

**Issue by huangxininchina** [pyxll/pyxll-jupyter#4]
Seems Excel for Mac version doens't support your "pyxll install" command, can you fix it? is it only for Windows or there is the problem in my setting?

**Comment by tonyroberts** [comment]
PyXLL requires Excel for Windows. To use it on a mac you would need to run a Windows VM, eg VirtualBox or Parallels.

Please see the system requirements here https://support.pyxll.com/hc/en-gb/articles/360036821433-What-are-the-System-Requirements-of-PyXLL-.
